/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewsLarRouteImport } from './routes/reviews.lar'
import { Route as ReviewsEndpointRouteImport } from './routes/reviews.endpoint'
import { Route as ReviewsContractualRouteImport } from './routes/reviews.contractual'
import { Route as DbOverallRouteImport } from './routes/db.overall'
import { Route as DbLarRouteImport } from './routes/db.lar'
import { Route as DbEndpointRouteImport } from './routes/db.endpoint'
import { Route as DbContractualRouteImport } from './routes/db.contractual'
import { Route as ConfigLarRouteImport } from './routes/config.lar'
import { Route as ConfigEndpointRouteImport } from './routes/config.endpoint'
import { Route as ConfigContractualRouteImport } from './routes/config.contractual'
import { Route as DbReportIdRouteImport } from './routes/db.report.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsLarRoute = ReviewsLarRouteImport.update({
  id: '/reviews/lar',
  path: '/reviews/lar',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsEndpointRoute = ReviewsEndpointRouteImport.update({
  id: '/reviews/endpoint',
  path: '/reviews/endpoint',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsContractualRoute = ReviewsContractualRouteImport.update({
  id: '/reviews/contractual',
  path: '/reviews/contractual',
  getParentRoute: () => rootRouteImport,
} as any)
const DbOverallRoute = DbOverallRouteImport.update({
  id: '/db/overall',
  path: '/db/overall',
  getParentRoute: () => rootRouteImport,
} as any)
const DbLarRoute = DbLarRouteImport.update({
  id: '/db/lar',
  path: '/db/lar',
  getParentRoute: () => rootRouteImport,
} as any)
const DbEndpointRoute = DbEndpointRouteImport.update({
  id: '/db/endpoint',
  path: '/db/endpoint',
  getParentRoute: () => rootRouteImport,
} as any)
const DbContractualRoute = DbContractualRouteImport.update({
  id: '/db/contractual',
  path: '/db/contractual',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigLarRoute = ConfigLarRouteImport.update({
  id: '/config/lar',
  path: '/config/lar',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigEndpointRoute = ConfigEndpointRouteImport.update({
  id: '/config/endpoint',
  path: '/config/endpoint',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigContractualRoute = ConfigContractualRouteImport.update({
  id: '/config/contractual',
  path: '/config/contractual',
  getParentRoute: () => rootRouteImport,
} as any)
const DbReportIdRoute = DbReportIdRouteImport.update({
  id: '/db/report/$id',
  path: '/db/report/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/config/contractual': typeof ConfigContractualRoute
  '/config/endpoint': typeof ConfigEndpointRoute
  '/config/lar': typeof ConfigLarRoute
  '/db/contractual': typeof DbContractualRoute
  '/db/endpoint': typeof DbEndpointRoute
  '/db/lar': typeof DbLarRoute
  '/db/overall': typeof DbOverallRoute
  '/reviews/contractual': typeof ReviewsContractualRoute
  '/reviews/endpoint': typeof ReviewsEndpointRoute
  '/reviews/lar': typeof ReviewsLarRoute
  '/db/report/$id': typeof DbReportIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/config/contractual': typeof ConfigContractualRoute
  '/config/endpoint': typeof ConfigEndpointRoute
  '/config/lar': typeof ConfigLarRoute
  '/db/contractual': typeof DbContractualRoute
  '/db/endpoint': typeof DbEndpointRoute
  '/db/lar': typeof DbLarRoute
  '/db/overall': typeof DbOverallRoute
  '/reviews/contractual': typeof ReviewsContractualRoute
  '/reviews/endpoint': typeof ReviewsEndpointRoute
  '/reviews/lar': typeof ReviewsLarRoute
  '/db/report/$id': typeof DbReportIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/config/contractual': typeof ConfigContractualRoute
  '/config/endpoint': typeof ConfigEndpointRoute
  '/config/lar': typeof ConfigLarRoute
  '/db/contractual': typeof DbContractualRoute
  '/db/endpoint': typeof DbEndpointRoute
  '/db/lar': typeof DbLarRoute
  '/db/overall': typeof DbOverallRoute
  '/reviews/contractual': typeof ReviewsContractualRoute
  '/reviews/endpoint': typeof ReviewsEndpointRoute
  '/reviews/lar': typeof ReviewsLarRoute
  '/db/report/$id': typeof DbReportIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/config/contractual'
    | '/config/endpoint'
    | '/config/lar'
    | '/db/contractual'
    | '/db/endpoint'
    | '/db/lar'
    | '/db/overall'
    | '/reviews/contractual'
    | '/reviews/endpoint'
    | '/reviews/lar'
    | '/db/report/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/config/contractual'
    | '/config/endpoint'
    | '/config/lar'
    | '/db/contractual'
    | '/db/endpoint'
    | '/db/lar'
    | '/db/overall'
    | '/reviews/contractual'
    | '/reviews/endpoint'
    | '/reviews/lar'
    | '/db/report/$id'
  id:
    | '__root__'
    | '/'
    | '/config/contractual'
    | '/config/endpoint'
    | '/config/lar'
    | '/db/contractual'
    | '/db/endpoint'
    | '/db/lar'
    | '/db/overall'
    | '/reviews/contractual'
    | '/reviews/endpoint'
    | '/reviews/lar'
    | '/db/report/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfigContractualRoute: typeof ConfigContractualRoute
  ConfigEndpointRoute: typeof ConfigEndpointRoute
  ConfigLarRoute: typeof ConfigLarRoute
  DbContractualRoute: typeof DbContractualRoute
  DbEndpointRoute: typeof DbEndpointRoute
  DbLarRoute: typeof DbLarRoute
  DbOverallRoute: typeof DbOverallRoute
  ReviewsContractualRoute: typeof ReviewsContractualRoute
  ReviewsEndpointRoute: typeof ReviewsEndpointRoute
  ReviewsLarRoute: typeof ReviewsLarRoute
  DbReportIdRoute: typeof DbReportIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/lar': {
      id: '/reviews/lar'
      path: '/reviews/lar'
      fullPath: '/reviews/lar'
      preLoaderRoute: typeof ReviewsLarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/endpoint': {
      id: '/reviews/endpoint'
      path: '/reviews/endpoint'
      fullPath: '/reviews/endpoint'
      preLoaderRoute: typeof ReviewsEndpointRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/contractual': {
      id: '/reviews/contractual'
      path: '/reviews/contractual'
      fullPath: '/reviews/contractual'
      preLoaderRoute: typeof ReviewsContractualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/db/overall': {
      id: '/db/overall'
      path: '/db/overall'
      fullPath: '/db/overall'
      preLoaderRoute: typeof DbOverallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/db/lar': {
      id: '/db/lar'
      path: '/db/lar'
      fullPath: '/db/lar'
      preLoaderRoute: typeof DbLarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/db/endpoint': {
      id: '/db/endpoint'
      path: '/db/endpoint'
      fullPath: '/db/endpoint'
      preLoaderRoute: typeof DbEndpointRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/db/contractual': {
      id: '/db/contractual'
      path: '/db/contractual'
      fullPath: '/db/contractual'
      preLoaderRoute: typeof DbContractualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/lar': {
      id: '/config/lar'
      path: '/config/lar'
      fullPath: '/config/lar'
      preLoaderRoute: typeof ConfigLarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/endpoint': {
      id: '/config/endpoint'
      path: '/config/endpoint'
      fullPath: '/config/endpoint'
      preLoaderRoute: typeof ConfigEndpointRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/contractual': {
      id: '/config/contractual'
      path: '/config/contractual'
      fullPath: '/config/contractual'
      preLoaderRoute: typeof ConfigContractualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/db/report/$id': {
      id: '/db/report/$id'
      path: '/db/report/$id'
      fullPath: '/db/report/$id'
      preLoaderRoute: typeof DbReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfigContractualRoute: ConfigContractualRoute,
  ConfigEndpointRoute: ConfigEndpointRoute,
  ConfigLarRoute: ConfigLarRoute,
  DbContractualRoute: DbContractualRoute,
  DbEndpointRoute: DbEndpointRoute,
  DbLarRoute: DbLarRoute,
  DbOverallRoute: DbOverallRoute,
  ReviewsContractualRoute: ReviewsContractualRoute,
  ReviewsEndpointRoute: ReviewsEndpointRoute,
  ReviewsLarRoute: ReviewsLarRoute,
  DbReportIdRoute: DbReportIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
